"""
Persistence abstraction.

Defines the Store protocol (the contract shared by all persistence backends).
"""

from __future__ import annotations

from typing import Protocol

from ..core.entities import Agent, Run, RunEvent, Thread


class Store(Protocol):
    """
    Persistence interface for all three core entities.
    Any implementation (in-memory, Postgres, SQLite) must satisfy this.
    """

    # -- Agent CRUD --
    def save_agent(self, agent: Agent) -> None: ...
    def get_agent(self, agent_id: str) -> Agent | None: ...
    def list_agents(self) -> list[Agent]: ...
    def delete_agent(self, agent_id: str) -> None: ...

    # -- Thread CRUD --
    def save_thread(self, thread: Thread) -> None: ...
    def get_thread(self, thread_id: str) -> Thread | None: ...
    def list_threads(self) -> list[Thread]: ...
    def delete_thread(self, thread_id: str) -> None: ...

    # -- Run CRUD --
    def save_run(self, run: Run) -> None: ...
    def get_run(self, run_id: str) -> Run | None: ...
    def list_runs(self, thread_id: str) -> list[Run]: ...

    # -- Run event log --
    def save_run_event(self, event: RunEvent) -> None: ...
    def list_run_events(
        self,
        run_id: str,
        *,
        after_seq: int = 0,
        limit: int = 1000,
    ) -> list[RunEvent]: ...
    def get_latest_run_event_seq(self, run_id: str) -> int: ...
